# Generated by Django 4.2 on 2023-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название игры')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата загрузки торрента')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Обложка игры')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('developer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разработчик')),
                ('interface_language', models.IntegerField(blank=True, choices=[(1, 'Русский'), (2, 'Английский'), (0, 'Польский'), (3, 'Румынский')], null=True, verbose_name='Язык интерфейса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание игры')),
                ('os', models.CharField(blank=True, max_length=255, null=True, verbose_name='Операционная система')),
                ('processor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Процессор')),
                ('ram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оперативная память')),
                ('video_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видеокарта')),
                ('free_memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место на жестком диске')),
            ],
            options={
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]