# Generated by Django 4.2 on 2023-05-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_games_categories_games_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=255, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
            },
        ),
        migrations.CreateModel(
            name='OperationSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=255, verbose_name='Операционная система')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
            },
        ),
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(max_length=255, verbose_name='Процессор')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='VideoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_card_name', models.CharField(max_length=255, verbose_name='Видеокарта')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='games',
            name='categories',
            field=models.ManyToManyField(to='core.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='games',
            name='ram',
            field=models.IntegerField(blank=True, choices=[(0, '< 2GB'), (1, '2 GB'), (2, '4 GB'), (3, '6 GB'), (4, '8 GB'), (5, '10 GB'), (6, '12 GB'), (7, '14 GB'), (8, '16 GB')], null=True, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='games',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.developers', verbose_name='Разработчик'),
        ),
        migrations.AlterField(
            model_name='games',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.operationsystems', verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='games',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.processors', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='games',
            name='video_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.videocards', verbose_name='Видеокарта'),
        ),
    ]
