# Generated by Django 4.2 on 2023-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_developers_operationsystems_processors_videocards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='download_counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество скачиваний'),
        ),
        migrations.AddField(
            model_name='games',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка пользователей'),
        ),
    ]
