# Generated by Django 4.2 on 2023-05-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_games_download_counter_games_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='download_counter',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Количество скачиваний'),
        ),
        migrations.AlterField(
            model_name='games',
            name='score',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Оценка пользователей'),
        ),
    ]
