# Generated by Django 4.2 on 2023-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_games_download_counter_alter_games_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='download_counter',
        ),
        migrations.RemoveField(
            model_name='games',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='games',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка на игру'),
        ),
        migrations.AddField(
            model_name='games',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='score',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Популярность игры'),
        ),
    ]
