# Generated by Django 4.2 on 2023-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_games_download_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='price_with_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена игры со скидкой'),
        ),
        migrations.AlterField(
            model_name='games',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка на игру в процентах'),
        ),
    ]
