# Generated by Django 4.2 on 2023-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_games_price_with_discount_alter_games_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='price_with_discount',
        ),
        migrations.AddField(
            model_name='games',
            name='trailer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Трейлер игры'),
        ),
    ]
