# Generated by Django 4.2 on 2023-05-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_games_price_with_discount_games_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='trailer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Трейлер игры (ссылка iframe youtube)'),
        ),
        migrations.CreateModel(
            name='Screenchots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto_set', to='core.games', verbose_name='Игры')),
            ],
            options={
                'verbose_name': 'Cкриншот',
                'verbose_name_plural': 'Cкриншоты',
            },
        ),
    ]
