# Generated by Django 4.2 on 2023-05-15 09:01

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0010_alter_games_trailer_screenchots'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenchots',
            name='img',
            field=filer.fields.image.FilerImageField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
