# Generated by Django 4.2 on 2023-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_screenchots_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release_date',
            field=models.DateTimeField(verbose_name='Дата выпуска'),
        ),
    ]
