# Generated by Django 4.2 on 2023-05-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_games_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release_date',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
    ]
