# Generated by Django 4.2 on 2023-05-16 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_interfacelanguage_alter_games_interface_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='interface_language',
        ),
    ]
