# Generated by Django 4.2 on 2023-05-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_games_interface_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='interface_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.interfacelanguage', verbose_name='Язык интерфейса'),
        ),
    ]
