# Generated by Django 4.2 on 2023-05-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_games_interface_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=255, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='main_image',
            field=models.ImageField(upload_to='images/', verbose_name='Обложка игры'),
        ),
    ]
