# Generated by Django 4.2 on 2023-05-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_games_game_name_alter_games_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='price_without_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена игры со скидкой'),
        ),
    ]
