# Generated by Django 4.2 on 2023-05-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_games_price_without_discount_alter_games_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='price_without_discount',
        ),
    ]
