# Generated by Django 4.2 on 2023-05-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_games_price_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='show_in_slider',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Показывать на главной странице в слайдере'),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.review', verbose_name='Родитель'),
        ),
    ]
