# Generated by Django 4.2 on 2023-05-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image_alter_profile_user'),
        ('core', '0023_rename_movie_review_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='Пользователь'),
        ),
    ]
