# Generated by Django 4.2 on 2023-05-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image_alter_profile_user'),
        ('core', '0025_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='Пользователь'),
        ),
    ]
