# Generated by Django 4.2 on 2023-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Оплаченый'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Итого'),
        ),
    ]
