# Generated by Django 4.2 on 2023-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cart_payed_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Оплаченый'),
        ),
    ]
