# Generated by Django 4.2 on 2023-05-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='product',
            new_name='game',
        ),
    ]
